// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8glS6sP__t_hq6uXD54su0IrpKyM1VuQ',
    appId: '1:14839096579:web:dd75a0037a0c1a7c4bb536',
    messagingSenderId: '14839096579',
    projectId: 'authentication-693cc',
    authDomain: 'authentication-693cc.firebaseapp.com',
    storageBucket: 'authentication-693cc.appspot.com',
    measurementId: 'G-S8EW1E57BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjickpd3L0Se3IZgQwcR7ke3TGag5hdcc',
    appId: '1:14839096579:android:e0adaade56a171684bb536',
    messagingSenderId: '14839096579',
    projectId: 'authentication-693cc',
    storageBucket: 'authentication-693cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPXyGM3lMUDRJgOAOo3Fx3N0aIsqYCORc',
    appId: '1:14839096579:ios:1832fb7f892b2fae4bb536',
    messagingSenderId: '14839096579',
    projectId: 'authentication-693cc',
    storageBucket: 'authentication-693cc.appspot.com',
    androidClientId: '14839096579-3i7to6c7k1ebum82j6nblm9ub8vlajk3.apps.googleusercontent.com',
    iosClientId: '14839096579-cci7a3hksnn6j62tf40j08q2173r40iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlesignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPXyGM3lMUDRJgOAOo3Fx3N0aIsqYCORc',
    appId: '1:14839096579:ios:369b52b7d6b4994f4bb536',
    messagingSenderId: '14839096579',
    projectId: 'authentication-693cc',
    storageBucket: 'authentication-693cc.appspot.com',
    androidClientId: '14839096579-3i7to6c7k1ebum82j6nblm9ub8vlajk3.apps.googleusercontent.com',
    iosClientId: '14839096579-ia0jrinr8g4g2ga2mlqqelvkl6s58mub.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlesignin.RunnerTests',
  );
}
